      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*1 CSTRING(100)
C
C INITALIZE THE RANDOM NUMBER GENERATOR
C READ THE NUMBER OF CHARACTERS IN THE STRING AND MUTATION NUMBER
C
      READ(5,*) ISEED1,ISEED2
C   JACOB: I commented out the echoing of the input values
C      WRITE(6,*) ISEED1,ISEED2
      CALL RSEED(ISEED1,ISEED2)

C JACOB: Added loop until quit with negative mutation number
C JACOB: Input string length and mutation number

10      READ(5,*) MAX,IMUT
C   JACOB: I commented out the echoing of the input values
C      WRITE(6,*) MAX,IMUT

C JACOB: apparently I have to use a nastly GOTO rather than a while loop?

      IF (IMUT .LE. 0) GO TO 20  ! Exit loop if IMUT <= 0


C JACOB: Input SMILES String
      READ(5,'(100A1)') (CSTRING(J),J=1,MAX)
C   JACOB: I commented out the echoing of the input values
C      WRITE(6,'(100A1)') (CSTRING(J),J=1,MAX)
C
C GENERATE NEW MOLECULES FROM THE CURRENT MOLECULE
C

      IF(IMUT.EQ.1) CALL MUTATE1(CSTRING,MAX)
      IF(IMUT.EQ.2) CALL MUTATE2(CSTRING,MAX)
      IF(IMUT.EQ.3) CALL MUTATE3(CSTRING,MAX)
      IF(IMUT.EQ.4) CALL MUTATE4(CSTRING,MAX)
      IF(IMUT.EQ.5) CALL MUTATE5(CSTRING,MAX)
      IF(IMUT.EQ.6) CALL MUTATE6(CSTRING,MAX)
      IF(IMUT.EQ.7) CALL MUTATE7(CSTRING,MAX)
      
C JACOB: Ending the "loop" that uses GOTO
      GO TO 10  ! Loop back to the beginning
20    CONTINUE  ! End of loop
      
      END
C
C COMPILE WITH /CHECK=NOOVER ON VAX
C
      FUNCTION RNDMF(X)
      COMMON/RAN/IX,IY,ITAB(128)
      INTEGER IX,IY,ITAB
      DOUBLE PRECISION RNDMF
C
C COMPUTE A RANDOM NUMBER [0,1] USING THE LINEAR CONFLUENT METHOD
C
      IY=IY*65539
      IF(IY) 5,6,6
    5 IY=IY+2147483647+1
    6 IT=IY*.591389E-07+1.
C IBM GIVES THIS CONSTANT AS .4656613E-9 BUT I HAVE DROPPED THE 3 TO
C AVOID EVER GETTING A NUMBER EQUAL TO 1
      RNDMF=ITAB(IT)*.465661E-9
      IX=IX*65549
      IF(IX)15,16,16
   15 IX=IX+2147483647+1
   16 ITAB(IT)=IX
      RETURN
      END
C
      SUBROUTINE RSEED(IA,IB)
      COMMON/RAN/IX,IY,ITAB(128)
      INTEGER IX,IY,ITAB
C
C SET UP A FEW THINGS
C
      IX=2*(IA/2)+1
      IY=2*(IB/2)+1
      DO 30 I=1,128
      IX=IX*65549
      IF(IX) 5,6,6
    5 IX=IX+2147483647+1
    6 ITAB(I)=IX
   30 CONTINUE
      RETURN
      END
C
      SUBROUTINE FINDA(XSTRING,MAX,JTEMP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CHAR,XSTRING(100)
C
C ON INPUT, JTEMP IS THE POSITION IN THE STRING TO LOOK FOR AN ATOM
C ON OUTPUT, JTEMP IS THE POSITION IN THE STRING AFTER THE ATOM
C
10    CONTINUE
      CHAR=XSTRING(JTEMP)
C CHAR IS AN ATOM
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'O'.OR.CHAR.EQ.'N') THEN
C THIS PART IS ADDED TO MAKE SURE THE NEW ATOM DOESN'T BREAK A RING
20      CONTINUE
        IF(XSTRING(JTEMP+1).EQ.'1'.OR.XSTRING(JTEMP+1).EQ.'2'.OR.
     1     XSTRING(JTEMP+1).EQ.'3') THEN
          JTEMP=JTEMP+1
C          WRITE(6,*) "UPDATE JTEMP",JTEMP
          GO TO 20
        ENDIF
C THIS PART IS ADDED TO MAKE SURE THE NEW ATOM DOESN'T BREAK A BRANCH
        IF(XSTRING(JTEMP+1).EQ.'(') THEN
30        CONTINUE
          JTEMP=JTEMP+1
          IF(XSTRING(JTEMP+1).NE.')') GO TO 30
C          WRITE(6,*) "UPDATE2 JTEMP",JTEMP
        ENDIF
      ELSE
C CHAR WAS SOMETHING ELSE SO INCREASE JTEMP
        JTEMP=JTEMP+1
        IF(JTEMP.GT.MAX) RETURN
        GO TO 10
      ENDIF
      RETURN
      END
C
      SUBROUTINE FINDB(XSTRING,MAX,JTEMP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CHAR,XSTRING(100)
C
C ON INPUT, JTEMP IS THE POSITION IN THE STRING TO LOOK FOR A BOND
C ON OUTPUT, JTEMP IS THE POSITION IN THE STRING OF THE BOND
C
10    CONTINUE
      CHAR=XSTRING(JTEMP)
C CHAR IS A BOND
      IF(CHAR.EQ.'-'.OR.CHAR.EQ.'='.OR.CHAR.EQ.'#') THEN
        RETURN
      ELSE
C CHAR WAS SOMETHING ELSE SO INCREASE JTEMP
        JTEMP=JTEMP+1
        IF(JTEMP.GT.MAX) RETURN
        GO TO 10
      ENDIF
      RETURN
      END
C
      SUBROUTINE FINDC(XSTRING,MAX,JTEMP)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CHAR,XSTRING(100)
C
C ON INPUT, JTEMP IS THE POSITION IN THE STRING TO LOOK FOR AN ATOM
C ON OUTPUT, JTEMP IS THE POSITION IN THE STRING OF THE ATOM
C
10    CONTINUE
      CHAR=XSTRING(JTEMP)
C CHAR IS AN ATOM
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'O'.OR.CHAR.EQ.'N') THEN
        RETURN
      ELSE
C CHAR WAS SOMETHING ELSE SO INCREASE JTEMP
        JTEMP=JTEMP+1
        IF(JTEMP.GT.MAX) RETURN
        GO TO 10
      ENDIF
      RETURN
      END
C

      SUBROUTINE MUTATE1(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100),CHAR
      CHARACTER*1 BOND(100)
      INTEGER IBOND(100)
C
C GENERATE A MUTATION IN A MOLECULE (CHANGE BOND TYPE)
C
C REWIND 21 : JACOB: I commented this out
      NBOND=0
      DO 10 I=1,IMAX
      CHAR=CSTRING(I)
      IF(CHAR.EQ.'-'.OR.CHAR.EQ.'='.OR.CHAR.EQ.'#') THEN
        NBOND=NBOND+1
        BOND(NBOND)=CHAR
        IBOND(NBOND)=I
      ENDIF
10    CONTINUE
C      WRITE(6,*) "NBOND = ",NBOND
C      WRITE(6,*) (IBOND(I),I=1,NBOND)
C      WRITE(6,'(100A1)') (BOND(I),I=1,NBOND)
C
      MAX=IMAX
      ICOUNT=0
100   CONTINUE
      DO 110 I=1,IMAX
      XSTRING(I)=CSTRING(I)
110   CONTINUE
C
      JTEMP=NBOND*RNDMF(0.0)+1
C      WRITE(6,*) "IN MUTATE1 - CHANGE BOND TYPE",JTEMP
      KTEMP=2*RNDMF(0.0)+1
C      WRITE(6,'(100A1)') BOND(KTEMP)
C      WRITE(6,*) "KTEMP",KTEMP
      IF(BOND(JTEMP).EQ.'-') THEN
        XSTRING(IBOND(JTEMP))='='
        IF(KTEMP.EQ.2) XSTRING(IBOND(JTEMP))='#'
      ENDIF
      IF(BOND(JTEMP).EQ.'=') THEN
        XSTRING(IBOND(JTEMP))='-'
        IF(KTEMP.EQ.2) XSTRING(IBOND(JTEMP))='#'
      ENDIF
      IF(BOND(JTEMP).EQ.'#') THEN
        XSTRING(IBOND(JTEMP))='-'
        IF(KTEMP.EQ.2) XSTRING(IBOND(JTEMP))='='
      ENDIF
C
C CHECK IF WE HAVE A VALID MOLECULE
C
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
C      WRITE(6,*) "VAL = ",VAL
      IF(VAL.LT.999.0) THEN
        IMAX=MAX
        DO 120 I=1,MAX
        CSTRING(I)=XSTRING(I)
120     CONTINUE
C        WRITE(21,*) MAX
C        WRITE(21,'(100A1)') (CSTRING(J),J=1,MAX)
        RETURN
      ENDIF
      ICOUNT=ICOUNT+1
C      WRITE(6,*) "ICOUNT =",ICOUNT
      IF(ICOUNT.LT.10) GO TO 100
C      WRITE(21,*) 1
C      WRITE(21,'(100A1)') "X"
      RETURN
      END
C
      SUBROUTINE MUTATE2(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100),CHAR
      CHARACTER*1 ATOM(100)
      INTEGER IATOM(100)
C
C GENERATE A MUTATION IN A MOLECULE (ADD NEW ATOM)
C
C      REWIND 22
      NATOM=0
      DO 10 I=1,IMAX
      CHAR=CSTRING(I)
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'O'.OR.CHAR.EQ.'N') THEN
        NATOM=NATOM+1
        ATOM(NATOM)=CHAR
        IATOM(NATOM)=I
      ENDIF
10    CONTINUE
C      WRITE(6,*) "NATOM = ",NATOM
C      WRITE(6,*) (IATOM(I),I=1,NATOM)
C      WRITE(6,'(100A1)') (ATOM(I),I=1,NATOM)
C
      ICOUNT=0
100   CONTINUE
      DO 110 I=1,IMAX
      XSTRING(I)=CSTRING(I)
110   CONTINUE
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IMAX)
C
      JTEMP=NATOM*RNDMF(0.0)+1
      KTEMP=3*RNDMF(0.0)+1
      LTEMP=3*RNDMF(0.0)+1
C      WRITE(6,*) "IN MUTATE2 - ADD NEW ATOM",JTEMP,KTEMP,LTEMP
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IMAX)
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IATOM(JTEMP))
C      WRITE(6,*) IATOM(JTEMP),IMAX,IATOM(JTEMP)+1
      DO 120 JJJ=IMAX,IATOM(JTEMP)+1,-1
      XSTRING(JJJ+2)=XSTRING(JJJ)
120   CONTINUE
      IF(KTEMP.EQ.1) XSTRING(IATOM(JTEMP)+1)='-'
      IF(KTEMP.EQ.2) XSTRING(IATOM(JTEMP)+1)='='
      IF(KTEMP.EQ.3) XSTRING(IATOM(JTEMP)+1)='#'
      IF(LTEMP.EQ.1) XSTRING(IATOM(JTEMP)+2)='C'
      IF(LTEMP.EQ.2) XSTRING(IATOM(JTEMP)+2)='O'
      IF(LTEMP.EQ.3) XSTRING(IATOM(JTEMP)+2)='N'
      MAX=IMAX+2
C
C CHECK IF WE HAVE A VALID MOLECULE
C
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
C      WRITE(6,*) "VAL = ",VAL
      IF(VAL.LT.999.0) THEN
        IMAX=MAX
        DO 130 I=1,MAX
        CSTRING(I)=XSTRING(I)
130     CONTINUE
C        WRITE(22,*) MAX
C        WRITE(22,'(100A1)') (CSTRING(J),J=1,MAX)
        RETURN
      ENDIF
      ICOUNT=ICOUNT+1
C      WRITE(6,*) "ICOUNT =",ICOUNT
      IF(ICOUNT.LT.10) GO TO 100
C      WRITE(22,*) 1
C      WRITE(22,'(100A1)') "X"
      RETURN
      END
C
      SUBROUTINE MUTATE3(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100),CHAR
      CHARACTER*1 ATOM(100)
      INTEGER IATOM(100)
C
C GENERATE A MUTATION IN A MOLECULE (ADD NEW ATOM AS BRANCH)
C
C      REWIND 23
      NATOM=0
      DO 10 I=1,IMAX
      CHAR=CSTRING(I)
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'O'.OR.CHAR.EQ.'N') THEN
        NATOM=NATOM+1
        ATOM(NATOM)=CHAR
        IATOM(NATOM)=I
      ENDIF
10    CONTINUE
C      WRITE(6,*) "NATOM = ",NATOM
C      WRITE(6,*) (IATOM(I),I=1,NATOM)
C      WRITE(6,'(100A1)') (ATOM(I),I=1,NATOM)
C
      ICOUNT=0
100   CONTINUE
      DO 110 I=1,IMAX
      XSTRING(I)=CSTRING(I)
110   CONTINUE
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IMAX)
C
      JTEMP=NATOM*RNDMF(0.0)+1
      KTEMP=3*RNDMF(0.0)+1
      LTEMP=3*RNDMF(0.0)+1
C      WRITE(6,*) "IN MUTATE3 - ADD NEW ATOM AS BRANCH",JTEMP,KTEMP,LTEMP
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IMAX)
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IATOM(JTEMP))
C      WRITE(6,*) IATOM(JTEMP),IMAX,IATOM(JTEMP)+1
      DO 120 JJJ=IMAX,IATOM(JTEMP)+1,-1
      XSTRING(JJJ+4)=XSTRING(JJJ)
120   CONTINUE
      XSTRING(IATOM(JTEMP)+1)='('
      IF(KTEMP.EQ.1) XSTRING(IATOM(JTEMP)+2)='-'
      IF(KTEMP.EQ.2) XSTRING(IATOM(JTEMP)+2)='='
      IF(KTEMP.EQ.3) XSTRING(IATOM(JTEMP)+2)='#'
      IF(LTEMP.EQ.1) XSTRING(IATOM(JTEMP)+3)='C'
      IF(LTEMP.EQ.2) XSTRING(IATOM(JTEMP)+3)='O'
      IF(LTEMP.EQ.3) XSTRING(IATOM(JTEMP)+3)='N'
      XSTRING(IATOM(JTEMP)+4)=')'
      MAX=IMAX+4
C
C CHECK IF WE HAVE A VALID MOLECULE
C
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
C      WRITE(6,*) "VAL = ",VAL
      IF(VAL.LT.999.0) THEN
        IMAX=MAX
        DO 130 I=1,MAX
        CSTRING(I)=XSTRING(I)
130     CONTINUE
C        WRITE(23,*) MAX
C        WRITE(23,'(100A1)') (CSTRING(J),J=1,MAX)
        RETURN
      ENDIF
      ICOUNT=ICOUNT+1
C      WRITE(6,*) "ICOUNT =",ICOUNT
      IF(ICOUNT.LT.10) GO TO 100
C      WRITE(23,*) 1
C      WRITE(23,'(100A1)') "X"
      RETURN
      END
C
      SUBROUTINE MUTATE4(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100),CHAR,CHAR2,CHAR3
      CHARACTER*1 ATOM(100)
      INTEGER IATOM(100)
C
C GENERATE A MUTATION IN A MOLECULE (DELETE ATOM)
C
C      REWIND 24
      NATOM=0
      DO 10 I=1,IMAX
      CHAR=CSTRING(I)
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'O'.OR.CHAR.EQ.'N') THEN
        NATOM=NATOM+1
        ATOM(NATOM)=CHAR
        IATOM(NATOM)=I
      ENDIF
10    CONTINUE
C      WRITE(6,*) "NATOM = ",NATOM
C      WRITE(6,*) (IATOM(I),I=1,NATOM)
C      WRITE(6,'(100A1)') (ATOM(I),I=1,NATOM)
C
      ICOUNT=0
100   CONTINUE
      DO 200 I=1,IMAX
      XSTRING(I)=CSTRING(I)
200   CONTINUE
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,IMAX)
C
      JTEMP=NATOM*RNDMF(0.0)+1
C      WRITE(6,*) "IN MUTATE4 - DELETE ATOM",JTEMP
C 
C IF THE NEXT CHARACTER IS A NUMBER OR ( THEN PICK AGAIN
C
      CHAR2=XSTRING(IATOM(JTEMP)+1)
C      WRITE(6,'(100A1)') CHAR2
      IF(CHAR2.EQ.'1'.OR.CHAR2.EQ.'2'.OR.CHAR2.EQ.'3'.OR.
     1   CHAR2.EQ.'(') GO TO 2000
C
C OPTION 1: DELETE FIRST ATOM AND THE BOND AFTER IT
C
      IF(IATOM(JTEMP).EQ.1) THEN
C        WRITE(6,*) "DELETE FIRST ATOM",JTEMP
        IF(CHAR2.EQ.'-'.OR.CHAR2.EQ.'='.OR.CHAR2.EQ.'#') THEN
          DO 300 J=IATOM(JTEMP)+2,IMAX
          XSTRING(J-2)=XSTRING(J)
300       CONTINUE
          MAX=IMAX-2
C          WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
          GO TO 1000
        ELSE
C          WRITE(6,*) "PROBLEM WITH FIRST ATOM"
C          WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
          STOP
        ENDIF
      ENDIF
C
C OPTION 2: DELETE ATOM AND THE BOND BEFORE IT
C
      CHAR3=XSTRING(IATOM(JTEMP)-2)
C      WRITE(6,'(100A1)') CHAR3
      IF(CHAR2.EQ.')'.AND.CHAR3.EQ.'(') THEN
C        WRITE(6,'(100A1)') (XSTRING(J),J=1,IATOM(JTEMP)-3)
C        WRITE(6,'(100A1)') (XSTRING(J),J=IATOM(JTEMP)+2,IMAX)
        DO 400 J=IATOM(JTEMP)+2,IMAX
        XSTRING(J-4)=XSTRING(J)
400     CONTINUE
        MAX=IMAX-4
C        WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
        GO TO 1000
      ELSE
        DO 500 J=IATOM(JTEMP)+2,IMAX
        XSTRING(J-2)=XSTRING(J)
500     CONTINUE
        MAX=IMAX-2
C        WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
        GO TO 1000
      ENDIF
C
C CHECK IF WE HAVE A VALID MOLECULE
C
1000  CONTINUE
C      WRITE(6,'(100A1)') (XSTRING(JJJ),JJJ=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
C      WRITE(6,*) "VAL = ",VAL
C
      IF(VAL.LT.999.0) THEN
        IMAX=MAX
        DO 1010 I=1,MAX
        CSTRING(I)=XSTRING(I)
1010    CONTINUE
C        WRITE(24,*) MAX
C        WRITE(24,'(100A1)') (CSTRING(J),J=1,MAX)
        RETURN
      ENDIF
2000  CONTINUE
      ICOUNT=ICOUNT+1
C      WRITE(6,*) "ICOUNT =",ICOUNT
      IF(ICOUNT.LT.10) GO TO 100
C      WRITE(24,*) 1
C      WRITE(24,'(100A1)') "X"
      RETURN
      END

      SUBROUTINE MUTATE5(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100),CHAR
      CHARACTER*1 ATOM(100)
      INTEGER IATOM(100)
C
C GENERATE A MUTATION IN A MOLECULE (CHANGE ATOM TYPE)
C
C      REWIND 25
      NATOM=0
      DO 10 I=1,IMAX
      CHAR=CSTRING(I)
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'O'.OR.CHAR.EQ.'N') THEN
        NATOM=NATOM+1
        ATOM(NATOM)=CHAR
        IATOM(NATOM)=I
      ENDIF
10    CONTINUE
C      WRITE(6,*) "NATOM = ",NATOM
C      WRITE(6,*) (IATOM(I),I=1,NATOM)
C      WRITE(6,'(100A1)') (ATOM(I),I=1,NATOM)
C
      MAX=IMAX
      ICOUNT=0
100   CONTINUE
      DO 110 I=1,IMAX
      XSTRING(I)=CSTRING(I)
110   CONTINUE
C
      JTEMP=NATOM*RNDMF(0.0)+1
      WRITE(6,*) "IN MUTATE5 - CHANGE ATOM TYPE",JTEMP
      KTEMP=2*RNDMF(0.0)+1
C      WRITE(6,'(100A1)') ATOM(KTEMP)
C      WRITE(6,*) "KTEMP",KTEMP
      IF(ATOM(JTEMP).EQ.'C') THEN
        XSTRING(IATOM(JTEMP))='O'
        IF(KTEMP.EQ.2) XSTRING(IATOM(JTEMP))='N'
      ENDIF
      IF(ATOM(JTEMP).EQ.'O') THEN
        XSTRING(IATOM(JTEMP))='C'
        IF(KTEMP.EQ.2) XSTRING(IATOM(JTEMP))='N'
      ENDIF
      IF(ATOM(JTEMP).EQ.'N') THEN
        XSTRING(IATOM(JTEMP))='C'
        IF(KTEMP.EQ.2) XSTRING(IATOM(JTEMP))='O'
      ENDIF
C
C CHECK IF WE HAVE A VALID MOLECULE
C
C      WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
C      WRITE(6,*) "VAL = ",VAL
      IF(VAL.LT.999.0) THEN
        IMAX=MAX
        DO 120 I=1,MAX
        CSTRING(I)=XSTRING(I)
120     CONTINUE
C        WRITE(25,*) MAX
C        WRITE(25,'(100A1)') (CSTRING(J),J=1,MAX)
        RETURN
      ENDIF
      ICOUNT=ICOUNT+1
C      WRITE(6,*) "ICOUNT =",ICOUNT
      IF(ICOUNT.LT.10) GO TO 100
C      WRITE(25,*) 1
C      WRITE(25,'(100A1)') "X"
      RETURN
      END

C
      SUBROUTINE MUTATE6(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100),CHAR
      CHARACTER*1 NUMBER(3)
      DATA NUMBER /'1','2','3'/
C
C GENERATE A MUTATION IN A MOLECULE (DELETE RING)
C
C      WRITE(12,*) "IN MUTATE6 - DELETE RING"
C      WRITE(12,'(100A1)') (CSTRING(J),J=1,IMAX)
C
      MAX=IMAX
      NRING=0
      DO 10 J=1,MAX
      XSTRING(J)=CSTRING(J)
      IF(XSTRING(J).EQ.'1') NRING=NRING+1
      IF(XSTRING(J).EQ.'2') NRING=NRING+1
      IF(XSTRING(J).EQ.'3') NRING=NRING+1
10    CONTINUE
      IF(NRING.EQ.0) THEN
C        WRITE(6,*) "THERE ARE NO RINGS IN THIS MOLECULE"
C        WRITE(6,*) 1
        WRITE(6,'(100A1)') "X"
        RETURN
      ENDIF
C
C JTEMP IS THE NUMBER OF THE RING TO BE DELETED
C
      JTEMP=(NRING/2)*RNDMF(0.0)+1
C      WRITE(6,*) "NRING = ",NRING/2,JTEMP
      KTEMP=0
      DO 20 I=1,MAX
      CHAR=XSTRING(I)
      IF(CHAR.NE.NUMBER(JTEMP)) THEN
        KTEMP=KTEMP+1
        XSTRING(KTEMP)=CHAR
C RENUMBER LOOPS
        IF(JTEMP.EQ.1.AND.CHAR.EQ.NUMBER(2)) XSTRING(KTEMP)=NUMBER(1)
        IF(JTEMP.EQ.1.AND.CHAR.EQ.NUMBER(3)) XSTRING(KTEMP)=NUMBER(2)
        IF(JTEMP.EQ.2.AND.CHAR.EQ.NUMBER(3)) XSTRING(KTEMP)=NUMBER(2)
      ENDIF
20    CONTINUE
      MAX=MAX-2
C CHECK IF WE HAVE A VALID MOLECULE
C      WRITE(12,'(100A1)') (XSTRING(JJJ),JJJ=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
      IF(VAL.LT.999.9) THEN
C        WRITE(6,*) MAX
        WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
      ELSE
C        WRITE(6,*) 1
        WRITE(6,'(100A1)') "X"
      ENDIF
      RETURN
      END
C
      SUBROUTINE MUTATE7(CSTRING,IMAX)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 CSTRING(100),XSTRING(100)
      CHARACTER*1 NUMBER(3)
      INTEGER ADJ,RSIZE,RATOM
      COMMON/RINGS/ NATOM,RSIZE(3),RATOM(100),ADJ(100,100)
      DATA NUMBER /'1','2','3'/
C
C GENERATE A MUTATION IN A MOLECULE (DELETE A RING)
C JTEMP IS THE POSITION IN THAT STRING
C
C      WRITE(12,*) "IN MUTATE7 - ADD RING"
C      WRITE(12,'(100A1)') (CSTRING(J),J=1,IMAX)
C
      MAX=IMAX
      NRING=0
      DO 10 J=1,MAX
      XSTRING(J)=CSTRING(J)
      IF(XSTRING(J).EQ.'1') NRING=NRING+1
      IF(XSTRING(J).EQ.'2') NRING=NRING+1
      IF(XSTRING(J).EQ.'3') NRING=NRING+1
10    CONTINUE
      NRING=NRING/2+1
C      WRITE(12,*) "NRING =",NRING
      IF(NRING.EQ.0) THEN
C        WRITE(12,*) "NO RINGS FOUND"
C        WRITE(6,*) 1
        WRITE(6,'(100A1)') "X"
        RETURN
      ENDIF
      IF(NRING.GT.3) THEN
C        WRITE(12,*) "TOO MANY RINGS"
C        WRITE(6,*) 1
        WRITE(6,'(100A1)') "X"
        RETURN
      ENDIF
C
C RANDOMLY PLACE THE START OF THE RING
C
      JTEMP=MAX*RNDMF(0.0)+1
C      WRITE(6,*) "START OF RING",JTEMP
C
      CALL FINDA(XSTRING,MAX,JTEMP)
C      WRITE(6,*) "AFTER FINDA(#1)",JTEMP,MAX
      IF(JTEMP.GT.MAX) GO TO 200
      DO 20 JJJ=MAX,JTEMP+1,-1
      XSTRING(JJJ+1)=XSTRING(JJJ)
20    CONTINUE
      XSTRING(JTEMP+1)=NUMBER(NRING)
      MAX=MAX+1
C      WRITE(6,*) "END OF FIRST PART"
C      WRITE(6,'(100A1)') (XSTRING(JJJ),JJJ=1,MAX)
C
C PLACE END OF RING TO THE RIGHT OF THE START OF THE RING
C
      JTEMP=JTEMP+1
      RRR=RNDMF(0.0)
C      WRITE(6,*) MAX,JTEMP,RRR
      JTEMP=(MAX-JTEMP)*RRR+JTEMP
C      WRITE(6,*) "END OF RING GUESS ",JTEMP
      CALL FINDC(XSTRING,MAX,JTEMP)
C      WRITE(6,*) "AFTER FINDC(#2)",JTEMP
      IF(JTEMP.GT.MAX) GO TO 200
      DO 30 JJJ=MAX,JTEMP+1,-1
      XSTRING(JJJ+1)=XSTRING(JJJ)
30    CONTINUE
      XSTRING(JTEMP+1)=NUMBER(NRING)
      MAX=MAX+1
C      WRITE(6,*) "END OF SECOND PART"
C
C CHECK IF WE HAVE A VALID MOLECULE
C
200   CONTINUE
C      WRITE(12,'(100A1)') (XSTRING(J),J=1,MAX)
      CALL PROCESS(MAX,XSTRING,VAL)
      IF(VAL.LT.999.9) THEN
C        WRITE(6,*) MAX
        WRITE(6,'(100A1)') (XSTRING(J),J=1,MAX)
      ELSE
C        WRITE(6,*) 1
        WRITE(6,'(100A1)') "X"
      ENDIF
      RETURN
      END
C
      SUBROUTINE PROCESS(MAX,XSTRING,VAL)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*1 XSTRING(100),CHAR,CHAR2
      CHARACTER*1 NUMBER(3)
      COMMON /CONS/ BVAL1,BVAL2
      INTEGER NATOM,ATOM(50),RSIZE(3),RATOM(100)
      INTEGER NPAIR,PAIR(50,3),BTYPE
      INTEGER BRANCH,HEAD(50),NRING
      INTEGER MAXB(3),ADJ(50,50),MAXRING
      INTEGER IRING(3),JRING(3),RING(100),NEXT(100),IPOINT(100)
      INTEGER INODE(100),JNODE(100),FWDARC(100),ARCFIR(100),NCYC(100)
      DATA MAXRING /3/
      DATA NUMBER /'1','2','3'/
      DATA MAXB /4,2,3/
C NATOM IS THE NUMBER OF ATOMS (MAX=50)
C ATOM CONTAINS THE TYPE OF EACH ATOM (1=C,2=O,3=N)
C NPAIR IS THE NUMBER OF PAIRS AN ATOM HAS
C PAIR CONTAINS WHICH ATOMS ARE BONDED AND THE TYPE OF BOND
C BTYPE IS THE TYPE OF BOND (1=S,2=D,3=T)
C BRANCH IS THE CURRENT LEVEL
C HEAD IS THE LAST ATOM (STARTING ATOM IN BOND)
C ADJ CONTAINS THE CONNECTIONS BETWEEN THE ATOMS
C ARRAY MAXB CONTAINS THE MAXIMUM NUMBER OF BONDS OF EACH TYPE OF ATOM
C
C CHECK IF XSTRING IS A VALID MOLECULE
C IF IT IS, CALCULATE ITS VALUE
C
      VAL=999.9
      IF(MAX.EQ.0) RETURN
      IF(MAX.GT.50) RETURN
C
      DO 20 I=1,50
      HEAD(I)=-1
      RING(I)=0
20    CONTINUE
      DO 25 I=1,MAXRING
      IRING(I)=0
      JRING(I)=0
25    CONTINUE
      NRING=0
C
C FIRST CHARACTER MUST BE AN ATOM
C
      NATOM=0
      NPAIR=0
      BTYPE=1
      HEAD(1)=1
      BRANCH=1
      CHAR=XSTRING(1)
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'N'.OR.CHAR.EQ.'O') THEN
        NATOM=NATOM+1
        IF(CHAR.EQ.'C') ATOM(NATOM)=1
        IF(CHAR.EQ.'O') ATOM(NATOM)=2
        IF(CHAR.EQ.'N') ATOM(NATOM)=3
      ELSE
C        WRITE(6,*) "FIRST CHARACTER IS NOT AN ATOM"
        RETURN
      ENDIF
C
C LOOP OVER ALL OTHER CHARACTERS
C
      DO 100 I=2,MAX
C      WRITE(6,*) "STRING POSITION",I
      CHAR=XSTRING(I)
      CHAR2=XSTRING(I+1)
C      WRITE(6,'(100A1)') CHAR,CHAR2
C
C CHAR IS AN ATOM
C
      IF(CHAR.EQ.'C'.OR.CHAR.EQ.'N'.OR.CHAR.EQ.'O') THEN
        NATOM=NATOM+1
C        WRITE(6,*) "ATOM",NATOM
        IF(CHAR.EQ.'C') ATOM(NATOM)=1
        IF(CHAR.EQ.'O') ATOM(NATOM)=2
        IF(CHAR.EQ.'N') ATOM(NATOM)=3
        NPAIR=NPAIR+1
        PAIR(NPAIR,1)=HEAD(BRANCH)
        IF(HEAD(BRANCH).EQ.-1) PAIR(NPAIR,1)=HEAD(BRANCH-1)
        PAIR(NPAIR,2)=NATOM
        PAIR(NPAIR,3)=BTYPE
        HEAD(BRANCH)=NATOM
      ENDIF
C
C CHAR IS A BOND
C NEXT CHAR MUST BE AN ATOM
C
      IF(CHAR.EQ.'-') THEN
        BTYPE=1
        IF(CHAR2.NE.'C'.AND.CHAR2.NE.'N'.AND.CHAR2.NE.'O') RETURN
      ENDIF
      IF(CHAR.EQ.'=') THEN
        BTYPE=2
        IF(CHAR2.NE.'C'.AND.CHAR2.NE.'N'.AND.CHAR2.NE.'O') RETURN
      ENDIF
      IF(CHAR.EQ.'#') THEN
        BTYPE=3
        IF(CHAR2.NE.'C'.AND.CHAR2.NE.'N'.AND.CHAR2.NE.'O') RETURN
      ENDIF
C
C CHAR IS A LEFT PARENTHESIS "("
C NEXT CHAR MUST BE A BOND
C
      IF(CHAR.EQ.'(') THEN
        BRANCH=BRANCH+1
C        WRITE(6,*) "BRANCH (",BRANCH
        IF(CHAR2.NE.'-'.AND.CHAR2.NE.'='.AND.CHAR2.NE.'#') RETURN
      ENDIF
C
C CHAR IS A RIGHT PARENTHESIS ")"
C
      IF(CHAR.EQ.')') THEN
        HEAD(BRANCH)=-1
        BRANCH=BRANCH-1
C        WRITE(6,*) "BRANCH )",BRANCH
      ENDIF
C
C CHAR IS A NUMBER
C ASSUME THAT EACH RING HAS A UNIQUE NUMBER
C ASSUME THAT EACH RING IS ON A SINGLE BRANCH
C ASSUME THAT EACH RING CONTAINS 3 OR MORE ATOMS
C
      ITEMP=0
      DO 110 II=1,MAXRING
      IF(CHAR.EQ.NUMBER(II)) ITEMP=II
110   CONTINUE
      IF(ITEMP.GT.NRING) NRING=ITEMP
      IF(ITEMP.GT.0) THEN
C TWO RINGS FOUND WITH THE SAME NUMBER
        IF(IRING(ITEMP).GT.0.AND.JRING(ITEMP).GT.0) THEN
C          WRITE(6,*) "DUPLICATE RING FOUND",ITEMP
          RETURN
        ENDIF
C END OF RING
C RINGS IN SMILES ARE SINGLE BONDS
        IF(IRING(ITEMP).GT.0.AND.JRING(ITEMP).EQ.0) THEN
          NPAIR=NPAIR+1
          PAIR(NPAIR,1)=IRING(ITEMP)
          PAIR(NPAIR,2)=NATOM
          PAIR(NPAIR,3)=1
          JRING(ITEMP)=NATOM
        ENDIF
C NEW RING STARTS
        IF(IRING(ITEMP).EQ.0.AND.JRING(ITEMP).EQ.0) THEN
          IRING(ITEMP)=NATOM
        ENDIF
      ENDIF
100   CONTINUE
C      WRITE(6,*) "NRING",NRING
C
C CREATE ADJ MATRIX
C
      DO 200 I=1,NATOM
      DO 200 J=1,NATOM
      ADJ(I,J)=0
200   CONTINUE
      DO 210 K=1,NPAIR
      ADJ(PAIR(K,1),PAIR(K,2))=PAIR(K,3)
      ADJ(PAIR(K,2),PAIR(K,1))=PAIR(K,3)
210   CONTINUE
C      DO 220 I=1,NATOM
C      WRITE(6,*) (ADJ(I,J),J=1,NATOM)
C220   CONTINUE
C      WRITE(6,*) (ATOM(I),I=1,NATOM)
C
C CHECK THAT EACH ATOM DOESN'T HAVE TOO MANY BONDS
C
      DO 300 I=1,NATOM
      NBOND=0
      DO 310 J=1,NATOM
      NBOND=NBOND+ADJ(I,J)
310   CONTINUE
      IF(NBOND.GT.MAXB(ATOM(I))) THEN
C        WRITE(6,*) "TOO MANY BONDS",I
        RETURN
      ENDIF
      IF(NBOND.LT.1) RETURN
300   CONTINUE
C
C NUMBER OF ( AND ) MUST MATCH (BRANCH=1)
C
      IF(BRANCH.NE.1) THEN
C        WRITE(6,*) "PARENTHESES DO NOT MATCH"
        RETURN
      ENDIF
C
C CHECK THAT THE RING SIZE = 4, 5 OR 6
C
      M=0
      DO 400 I=1,NATOM
      DO 400 J=I,NATOM
      IF(ADJ(I,J).NE.0) THEN
        INODE(M+1)=I
        JNODE(M+1)=J
        INODE(M+2)=J
        JNODE(M+2)=I
        M=M+2
      ENDIF
400   CONTINUE
      DO 410 I=1,NATOM
      RATOM(I)=0
410   CONTINUE
C      WRITE(6,*) NATOM,M
C      WRITE(6,*) (INODE(JJJ),JJJ=1,M)
C      WRITE(6,*) (JNODE(JJJ),JJJ=1,M)
C
      CALL FCYCLE(NATOM,M,INODE,JNODE,NUMCYC,NUMCMP,NCYC,
     1  FWDARC,ARCFIR,NEXT,IPOINT,RSIZE,RATOM)
C      WRITE(6,*) "NUMBER OF RINGS ",NUMCYC
C      WRITE(6,*) (RSIZE(I),I=1,NUMCYC)
C      WRITE(6,*) (RATOM(I),I=1,NATOM)
      IF(NRING.NE.NUMCYC) THEN
C        WRITE(6,*) "NUMBER OF RINGS DOESN'T MATCH"
        RETURN
      ENDIF
      DO 420 I=1,NUMCYC
      IF(RSIZE(I).LT.4.OR.RSIZE(I).GT.6) THEN
C        WRITE(6,*) "WRONG SIZE RING"
        RETURN
      ENDIF
420   CONTINUE
C
C WE HAVE A VALID MOLECULE SO SET A NOMINAL VALUE
C
      VAL=1.0
      RETURN
      END
C
      SUBROUTINE FCYCLE(N,M,INODE,JNODE,NUMCYC,NUMCMP,NCYC,
     1  FWDARC,ARCFIR,NEXT,IPOINT,RSIZE,RATOM)
      INTEGER INODE(100),JNODE(100),NCYC(100),FWDARC(100),ARCFIR(100),
     1  NEXT(100),IPOINT(100)
      INTEGER RSIZE(3),RATOM(100)
      LOGICAL JOIN
C
C FIND A FUNDAMENTAL SET OF CYCLES
C REF: ALGORITHMS ON GRAPHS BY H.T. LAU
C
      N1=N-1
      K=0
      DO 20 I=1,N1
      ARCFIR(I)=K+1
      DO 10 J=1,M
      NODEU=INODE(J)
      NODEV=JNODE(J)
      IF((NODEU.EQ.I).AND.(NODEU.LT.NODEV)) THEN
        K=K+1
        FWDARC(K)=NODEV
      ELSE
        IF((NODEV.EQ.I).AND.(NODEV.LT.NODEU)) THEN
          K=K+1
          FWDARC(K)=NODEU
        ENDIF
      ENDIF
10    CONTINUE
20    CONTINUE
      ARCFIR(N)=M+1
C
      DO 30 IROOT=1,N
      NEXT(IROOT)=0
30    CONTINUE
      NUMCMP=0
      NUMCYC=0
C
      DO 100 IROOT=1,N
      IF(NEXT(IROOT).EQ.0) THEN
        NUMCMP=NUMCMP+1
        NEXT(IROOT)=-1
        INDEX=1
        IPOINT(1)=IROOT
        IEDGE=2
C
40      CONTINUE
        NODE3=IPOINT(INDEX)
        INDEX=INDEX-1
        NEXT(NODE3)=-NEXT(NODE3)
C
        DO 90 NODE2=1,N
        JOIN=.FALSE.
        IF(NODE2.NE.NODE3) THEN
          IF(NODE2.LT.NODE3) THEN
            NODEU=NODE2
            NODEV=NODE3
          ELSE
            NODEU=NODE3
            NODEV=NODE2
          ENDIF
          LOW=ARCFIR(NODEU)
          IUP=ARCFIR(NODEU+1)
          IF(IUP.GT.LOW) THEN
            IUP=IUP-1
            DO 50 K=LOW,IUP
            IF(FWDARC(K).EQ.NODEV) THEN
              JOIN=.TRUE.
              GO TO 60
            ENDIF
50          CONTINUE
          ENDIF
        ENDIF
60      CONTINUE
        IF(JOIN) THEN
          NODE1=NEXT(NODE2)
          IF(NODE1.EQ.0) THEN
            NEXT(NODE2)=-NODE3
            INDEX=INDEX+1
            IPOINT(INDEX)=NODE2
          ELSE
C GENERATE NEXT CYCLE
            IF(NODE1.LT.0) THEN
              NUMCYC=NUMCYC+1
              LEN=3
              NODE1=-NODE1
              NCYC(1)=NODE1
              NCYC(2)=NODE2
              NCYC(3)=NODE3
              I=NODE3
70            CONTINUE
              J=NEXT(I)
              IF(J.NE.NODE1) THEN
                LEN=LEN+1
                NCYC(LEN)=J
                I=J
                GO TO 70
              ENDIF
C OUTPUT A CYCLE
C              WRITE(6,*) "RING NUMBER",NUMCYC
C              WRITE(6,*) (NCYC(I),I=1,LEN)
              RSIZE(NUMCYC)=LEN
              DO 80 III=1,LEN
              RATOM(NCYC(III))=1
80            CONTINUE
            ENDIF
          ENDIF
        ENDIF
90      CONTINUE
        IEDGE=IEDGE+1
        IF((IEDGE.LE.N).AND.(INDEX.GT.0)) GO TO 40
        NEXT(IROOT)=0
        NODE3=IPOINT(1)
        NEXT(NODE3)=IABS(NEXT(NODE3))
      ENDIF
100   CONTINUE
      RETURN
      END
