package edu.southwestern.tasks.mario;

import java.util.List;

import ch.idsia.ai.agents.Agent;
import ch.idsia.mario.engine.level.Level;
import ch.idsia.tools.CmdLineOptions;
import ch.idsia.tools.EvaluationInfo;
import ch.idsia.tools.EvaluationOptions;
import competition.cig.robinbaumgarten.AStarAgent;
import edu.southwestern.MMNEAT.MMNEAT;
import edu.southwestern.evolution.genotypes.Genotype;
import edu.southwestern.parameters.CommonConstants;
import edu.southwestern.tasks.NoisyLonerTask;
import edu.southwestern.tasks.mario.level.MarioLevelUtil;
import edu.southwestern.util.datastructures.Pair;

/**
 * 
 * Evolve Mario levels using an agent,
 * like the Mario A* Agent, as a means of evaluating.
 * Levels can be generated by CPPNs or a GAN, but this is
 * done in child classes.
 * 
 * @author Jacob Schrum
 *
 * @param <T>
 */
public abstract class MarioLevelTask<T> extends NoisyLonerTask<T> {
	// There is space in each level that Mario cannot traverse because it is after the goal post.
	// This constant allows that space to be subtracted out.
	public static final int SPACE_AT_LEVEL_END = 225;
	public static boolean useProgressPlusJumpsFitness = true;
	
	private Agent agent;
	
	public MarioLevelTask() {
		// Replace this with a command line parameter
		agent = new AStarAgent();
		
		// Fitness
		if(useProgressPlusJumpsFitness) {
			MMNEAT.registerFitnessFunction("ProgressPlusJumps");
		} else {
			MMNEAT.registerFitnessFunction("ProgressPlusTime");
		}
        // Other scores
        MMNEAT.registerFitnessFunction("Distance", false);
        MMNEAT.registerFitnessFunction("Time", false);
        MMNEAT.registerFitnessFunction("Jumps", false);

	}
	
	@Override
	public int numObjectives() {
		// First maximize progress through the level.
		// If the level is cleared, then maximize the duration of the
		// level, which will indicate that it is challenging.
		return 1;  
	}
	
	public int numOtherScores() {
		return 3; // Distance, Time, and Jumps
	}

	@Override
	public double getTimeStamp() {
		return 0; // Not used
	}

	public abstract Level getMarioLevelFromGenotype(Genotype<T> individual);
	
	@Override
	public Pair<double[], double[]> oneEval(Genotype<T> individual, int num) {
		Level level = getMarioLevelFromGenotype(individual);
		agent.reset(); // Get ready to play a new level
		EvaluationOptions options = new CmdLineOptions(new String[]{});
		options.setAgent(agent);
        options.setLevel(level);
        options.setMaxFPS(true);
        options.setVisualization(CommonConstants.watch);
		List<EvaluationInfo> infos = MarioLevelUtil.agentPlaysLevel(options);
		// For now, assume a single evaluation
		EvaluationInfo info = infos.get(0);
		double distancePassed = info.lengthOfLevelPassedPhys;
		double totalDistanceInLevel = info.totalLengthOfLevelPhys;
		double time = info.timeSpentOnLevel;
		double jumps = info.jumpActionsPerformed;

		double[] otherScores = new double[] {distancePassed, time, jumps};
		
		if(distancePassed < totalDistanceInLevel - SPACE_AT_LEVEL_END) {
			// If level is not completed, score the amount of distance covered.
			// This is true whether time or jumps are added.
			return new Pair<double[],double[]>(new double[]{distancePassed}, otherScores);
		} else { // Level beaten
			if(useProgressPlusJumpsFitness) { // Add Jumps to favor harder levels requiring more jumping
				return new Pair<double[],double[]>(new double[]{distancePassed+jumps}, otherScores);
			} else { // Add in the time so that more complicated, challenging levels will be favored
				return new Pair<double[],double[]>(new double[]{distancePassed+time}, otherScores);
			}
		}
	}
	
}
