package edu.southwestern.tasks.loderunner;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import edu.southwestern.parameters.Parameters;
import edu.southwestern.tasks.mario.gan.GANProcess;
import edu.southwestern.tasks.mario.gan.reader.JsonReader;
import edu.southwestern.util.random.RandomNumbers;

/**
 * Runs the GAN process and the main method renders a single level that was generated by the GAN 
 * @author kdste
 *
 */
public class LodeRunnerGANUtil {
	//public static final int LODE_RUNNER_TILE_NUMBER = 8; //number of tiles in LodeRunner 
	//public static final int LATENT_VECTOR_SIZE = 10;//latent vector dimension
	public static final int LATENT_VECTOR_SIZE = 20;//latent vector dimension, 20 improved the model a lot 
	public static final int LODE_RUNNER_TILE_NUMBER = 6; //number of tiles in LodeRunner

	/**
	 * Renders a level that was generated by the GAN 
	 * @param args
	 * @throws IOException 
	 */
	public static void main(String[] args) throws IOException {
		GANProcess.type = GANProcess.GAN_TYPE.LODE_RUNNER; //sets GAN type to LodeRunner
		Parameters.initializeParameterCollections(new String[] {"GANInputSize:"+LATENT_VECTOR_SIZE});//input size is the size of the latent vector
		double[] latentVector = RandomNumbers.randomArray(LATENT_VECTOR_SIZE); //fills array of input size randomly
		List<List<Integer>> oneLevel = generateOneLevelListRepresentationFromGAN(latentVector); //one level to render
//		BufferedImage[] images = LodeRunnerRenderUtil.loadImages(LodeRunnerRenderUtil.LODE_RUNNER_TILE_PATH); //Initializes the array that hold the tile images
//		LodeRunnerRenderUtil.getBufferedImage(oneLevel, images);//rendered level and displays it in a window 
		BufferedImage[] images = LodeRunnerRenderUtil.loadImagesNoSpawn(LodeRunnerRenderUtil.LODE_RUNNER_TILE_PATH); //Initializes the array that hold the tile images
		LodeRunnerRenderUtil.getBufferedImage(oneLevel,images);//rendered level and displays it in a window 
		GANProcess.terminateGANProcess();
	}

	/**
	 * Gets a set of all of the levels from the latent vector 
	 * @param latentVector
	 * @return Set of all the levels
	 */
	public static List<List<List<Integer>>> getLevelListRepresentationFromGAN(double[] latentVector){
		latentVector = GANProcess.mapArrayToOne(latentVector); 
		// Generate room from vector
		try {
			GANProcess.getGANProcess().commSend("[" + Arrays.toString(latentVector) + "]");
		} catch (IOException e) {
			e.printStackTrace();
			System.exit(1); // Cannot continue without the GAN process
		}
		String level = GANProcess.getGANProcess().commRecv(); // Response to command just sent
		level = "["+level+"]"; // Wrap level in another json array
		List<List<List<Integer>>> levels = JsonReader.JsonToInt(level);
		return levels;
	}

	/**
	 * Gets one level from the list of levels, chooses the first one in the list  
	 * @param latentVector
	 * @return A single level 
	 */
	public static List<List<Integer>> generateOneLevelListRepresentationFromGAN(double[] latentVector) {
		List<List<List<Integer>>> levelInList = getLevelListRepresentationFromGAN(latentVector);
		List<List<Integer>> oneLevel = levelInList.get(0); // gets first level in the set  
		return oneLevel;
	}




}
